FROM alpine:3.11 AS build
MAINTAINER Ivan <ivan@zderadicka.eu>
ENV CARGO_ARGS=""
ENV FEATURES=""

RUN apk update &&\
    apk add git bash curl yasm build-base openssl-dev openssl-libs-static taglib-dev\
    wget zlib-dev zlib-static bzip2-static bzip2-dev rust cargo npm &&\
    mkdir /src &&\
    mkdir /.cargo &&\
    chmod a+rw /.cargo &&\
    mkdir /.npm &&\
    chmod a+rw /.npm
 
WORKDIR /src
ENV RUSTFLAGS="-C target-feature=+crt-static"
CMD  ["./_build_static.sh"]

