[package]
name = "col-util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap={version="4", features=["derive"]}
collection={path="../collection"}
env_logger="0.11"
anyhow="1.0.82"
libc="0.2"
