name: Release version

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  audioserve-build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - name: Build image
      run: docker build --tag izderadicka/audioserve .
    - name: Publish image
      run: |
        docker login -u ${{secrets.DOCKERHUB_USER}} -p ${{secrets.DOCKERHUB_PASSWORD}}
        docker push izderadicka/audioserve
  build-static:
    runs-on: ubuntu-24.04
    needs: audioserve-build
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Build static Binary
        run: |
          ./build_static.sh
      - name: Release static binary tar
        uses: softprops/action-gh-release@v3
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: _static_build/audioserve_static.tar.gz